name: "Fortify App and Release Name"
description: "Set the Fortify App and Release Name based on branch/PR and overrides"
inputs:
  default_fortify_app_name:
    required: true
    description: "Default Fortify Application Name"
  default_fortify_release_name:
    required: true
    description: "Default Fortify Release Name"
  app_name_postfix:
    required: false
    description: "Additional string to append to App Name to make it unique for a user"
    default: ""
outputs:
  app_name:
    description: "Fortify Application Name"
    value: ${{ steps.fortify-app-name.outputs.app_name }}
  release_name:
    description: "Fortify Release Name"
    value: ${{ steps.fortify-release-name.outputs.release_name }}
  parent_release_name:
    description: "Fortify Parent Release Name"
    value: ${{ steps.fortify-release-name.outputs.parent_release_name }}
runs:
  using: "composite"
  steps:
    - name: Check Out Source Code
      uses: actions/checkout@v3.3.0
    - name: Set Fortify App Name
      id: fortify-app-name
      shell: bash
      run: |
        if [[ -z "$APP_NAME_POSTFIX" ]]; then
          echo "::debug::Setting: '$DEFAULT_APP_NAME'"
          echo "$DEFAULT_APP_NAME" >> $GITHUB_OUTPUT
        else
          echo "::debug::Setting: '$OVERRIDE_APP_NAME'"
          echo "$OVERRIDE_APP_NAME" >> $GITHUB_OUTPUT
        fi
      env:
        APP_NAME_POSTFIX: ${{ inputs.app_name_postfix }}
        DEFAULT_APP_NAME: ${{ format('{0}={1}', 'app_name', inputs.default_fortify_app_name) }}
        OVERRIDE_APP_NAME: ${{ format('{0}={1} {2}', 'app_name', inputs.default_fortify_app_name, inputs.app_name_postfix) }}
    - name: Get branch names.
      id: branch-names
      uses: tj-actions/branch-names@v8
    - name: Set Fortify Release Name
      id: fortify-release-name
      shell: bash
      run: |
        echo "Git current branch name: ${CURRENT_BRANCH}"
        echo "::debug::release_name=${CURRENT_BRANCH}"         
        echo "release_name=${CURRENT_BRANCH}" >> $GITHUB_OUTPUT
        echo "Git parent branch name: ${PARENT_BRANCH}"
        echo "::debug::parent_release_name=${PARENT_BRANCH}"         
        echo "parent_release_name=${PARENT_BRANCH}" >> $GITHUB_OUTPUT
      env:
        CURRENT_BRANCH: ${{ steps.branch-names.outputs.current_branch }}
        #PARENT_BRANCH: ${{ steps.branch-names.outputs.ref_branch }}
        PARENT_BRANCH: "main" # hardcoded for now until we find a consistent way of calculating it
