drop table authority if exists;
drop table user if exists;
drop table user_authority if exists;
drop table product if exists;
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start with 1 increment by 1;

create table authority (
    id integer not null,
    name varchar(255),
    primary key (id)
);
create table user (
    id integer generated by default as identity,
    username varchar(255) not null,
    password varchar(255),
    date_created timestamp,
    name varchar(255) not null,
    email varchar(255) not null,
    mobile varchar(255) not null,
    enabled bit(1) not null,
    primary key (id)
);
create table user_authority (
    user_id integer not null,
    authority_id integer not null,
    primary key (user_id, authority_id)
);
create table product (
     id integer generated by default as identity,
     code varchar(255) not null,
     name varchar(255) not null,
     summary clob not null,
     description clob not null,
     image varchar(255),
     trade_price float not null,
     retail_price float not null,
     delivery_time integer not null,
     average_rating integer not null,
     available bit(1) not null,
     primary key (id)
);

alter table user add constraint UKuser_username unique (username);
alter table user_authority add constraint FKuser_authority_authority_id foreign key (authority_id) references authority;
alter table user_authority add constraint FKuser_authority_user_id foreign key (user_id) references user;
